# Generated by Django 6.0.3 on 2026-03-09 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Flight_Number', models.CharField(default='', max_length=6)),
                ('City', models.CharField(default='', max_length=100)),
                ('IATA_Code', models.CharField(default='', max_length=3)),
                ('Departure_Airport', models.CharField(default='', max_length=100)),
                ('Arrival_Airport', models.CharField(default='', max_length=100)),
                ('Departure_Time', models.DateTimeField()),
                ('Arrival_Time', models.DateTimeField()),
                ('Status', models.CharField(default='Scheduled', max_length=100)),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'constraints': [models.UniqueConstraint(fields=('Flight_Number', 'IATA_Code'), name='UniqueFlight')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Booking_Date', models.DateTimeField()),
                ('Status', models.CharField(default='', max_length=100)),
                ('Total_Price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Flight_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Flight', to='AirDBUK_App.flight')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
