# Generated by Django 6.0.3 on 2026-03-09 14:49

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirDBUK_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(default='', max_length=100)),
                ('Last_Name', models.CharField(default='', max_length=100)),
                ('DOB', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='Flight_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='AirDBUK_App.flight'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Total_Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Booking_Passenger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Booking_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_passengers', to='AirDBUK_App.booking')),
                ('Passenger_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_passengers', to='AirDBUK_App.passenger')),
            ],
            options={
                'verbose_name': 'Booking_Passenger',
                'verbose_name_plural': 'Booking_Passengers',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Payment_Date', models.DateTimeField()),
                ('Booking_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='AirDBUK_App.booking')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(default='', max_length=254)),
                ('Password', models.CharField(default='', max_length=25)),
                ('First_Name', models.CharField(default='', max_length=100)),
                ('Last_Name', models.CharField(default='', max_length=100)),
                ('Phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Role', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'constraints': [models.UniqueConstraint(fields=('Email', 'Phone'), name='UniqueUser')],
            },
        ),
        migrations.AddField(
            model_name='passenger',
            name='User_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passengers', to='AirDBUK_App.user'),
        ),
        migrations.AddField(
            model_name='booking',
            name='User_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='AirDBUK_App.user'),
        ),
    ]
