# Generated by Django 6.0.3 on 2026-03-11 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirDBUK_App', '0002_passenger_alter_booking_flight_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('City', models.CharField(default='', max_length=100)),
                ('IATA_Code', models.CharField(default='', max_length=3)),
                ('Name', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
            },
        ),
        migrations.RemoveConstraint(
            model_name='flight',
            name='UniqueFlight',
        ),
        migrations.AlterField(
            model_name='flight',
            name='Flight_Number',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Arrival_Airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arriving_flights', to='AirDBUK_App.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Departure_Airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departing_flights', to='AirDBUK_App.airport'),
        ),
        migrations.RemoveField(
            model_name='flight',
            name='City',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='IATA_Code',
        ),
    ]
