# Generated by Django 6.0.3 on 2026-03-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirDBUK_App', '0003_airport_remove_flight_uniqueflight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='Travel_Class',
            field=models.CharField(default='Economy', max_length=20),
        ),
    ]
