# Generated by Django 6.0.3 on 2026-03-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirDBUK_App', '0004_flight_travel_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='Flight_Number',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
