# Generated by Django 6.0.3 on 2026-03-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirDBUK_App', '0005_alter_flight_flight_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='DOB',
            field=models.DateField(),
        ),
    ]
