# Generated by Django 6.0.3 on 2026-03-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirDBUK_App', '0006_flight_price_alter_passenger_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='City',
            field=models.CharField(default='', max_length=255),
        ),
    ]
